name: Flutter Test CI


on:
  push: 
    branches-ignore: [] 
  pull_request: 
    branches-ignore: []

jobs:
  run_flutter_tests:
    name: Rodar Testes Flutter
    runs-on: ubuntu-latest 

    steps:
      
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' 
          channel: 'stable'
          cache: true 

      - name: Instalar dependências (se houver pubspec.yaml)
        run: flutter pub get

      - name: Rodar testes
        run: flutter test 
